  services:
    bd:
      container_name: bd
      image: postgres
      environment:
        POSTGRES_USER: usuario
        POSTGRES_PASSWORD: pa_w0rd
        POSTGRES_DB: productos_compras
      volumes:
        - datosPostgres:/var/lib/postgresql/data
      ports:
        - 5432:5432
      networks:
        - red
    back:
      build: ./BACKEND
      depends_on: 
        - bd
      container_name: back
      environment:
        - ConnectionStrings__DefaultConnection=Host=bd;Port=5432;Database=productos_compras;Username=usuario;Password=pa_w0rd
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - 8080:5000
      networks:
        - red

    front:
      build: ./FRONTEND
      depends_on: 
        - back
      container_name: front
      ports:
        - 4200:80
      volumes:
        - ./FRONTEND/productos-compras-full-stack/src:/app/src
        - ./FRONTEND/productos-compras-full-stack/dist/productos-compras-full-stack/browser:/usr/share/nginx/html
        - ./FRONTEND/nginx.conf/nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
        - red
  
  volumes:
    datosPostgres:

  networks:
    red:
      


