// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRODUCTOS_COMPRAS_FULL_STACK.Models;

#nullable disable

namespace PRODUCTOS_COMPRAS_FULL_STACK.Migrations
{
    [DbContext(typeof(ProductoOrdenContext))]
    partial class ProductoCompraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRODUCTOS_COMPRAS_FULL_STACK.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("total")
                        .HasColumnType("FLOAT");

                    b.HasKey("Id");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("PRODUCTOS_COMPRAS_FULL_STACK.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.Property<float>("Precio")
                        .HasColumnType("FLOAT");

                    b.Property<int>("stock")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("PRODUCTOS_COMPRAS_FULL_STACK.Models.ProductoOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("OrdenId", "ProductoId")
                        .IsUnique();

                    b.ToTable("ProductoOrden");
                });

            modelBuilder.Entity("PRODUCTOS_COMPRAS_FULL_STACK.Models.ProductoOrden", b =>
                {
                    b.HasOne("PRODUCTOS_COMPRAS_FULL_STACK.Models.Orden", "Orden")
                        .WithMany("ProductoOrdenes")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRODUCTOS_COMPRAS_FULL_STACK.Models.Producto", "Producto")
                        .WithMany("ProductoOrdenes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PRODUCTOS_COMPRAS_FULL_STACK.Models.Orden", b =>
                {
                    b.Navigation("ProductoOrdenes");
                });

            modelBuilder.Entity("PRODUCTOS_COMPRAS_FULL_STACK.Models.Producto", b =>
                {
                    b.Navigation("ProductoOrdenes");
                });
#pragma warning restore 612, 618
        }
    }
}
